<a href="https://colab.research.google.com/github/chungwa-Hani/CodeAlpha_Iris_Classification/blob/main/iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Project Overview

This project focuses on classifying Iris flowers into three different species: *Iris-setosa*, *Iris-versicolor*, and *Iris-virginica*.

The classification will be based on measurements of the flowers, including sepal length, sepal width, petal length, and petal width.

The project follows a typical machine learning workflow, beginning with data exploration and preparation, followed by exploratory data analysis, model development, prediction, and evaluation.

## 2. Problem Statement

The objective of this project is to develop a classification model that can accurately identify the species of an Iris flower based on its measured characteristics.

The model will use the available flower measurements as input features and predict one of three species:

* *Iris-setosa*
* *Iris-versicolor*
* *Iris-virginica*

## 3. Project Objectives

The main objectives of this project are to:

1. Load and inspect the Iris dataset.
2. Understand the structure and characteristics of the data.
3. Identify and address any data-quality issues.
4. Perform exploratory data analysis (EDA).
5. Visualize relationships between the flower measurements and species.
6. Prepare the data for machine learning.
7. Split the dataset into training and testing sets.
8. Train a classification model.
9. Make predictions on unseen test data.
10. Evaluate the performance of the classification model.
11. Interpret the results and draw conclusions.

## 4. Dataset Description

The Iris dataset contains measurements of Iris flowers belonging to three different species.

The main measurement variables are:

| Feature      | Description         |
| ------------ | ------------------- |
| Sepal Length | Length of the sepal |
| Sepal Width  | Width of the sepal  |
| Petal Length | Length of the petal |
| Petal Width  | Width of the petal  |

The target variable is the Iris flower species.

The dataset also contains an `Id` column that identifies individual records.

## 5. Importing required libraries

In [3]:
## Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

## 6. Loading the Dataset

In [6]:
# Loding the iris dataset
df = pd.read_csv("/content/Iris.csv")

In [7]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

## 7. Initial Data Inspection

Before cleaning or analysing the dataset, it is important to inspect its structure and contents.

The initial inspection will help us determine:

* The number of observations and variables.
* The data types of each variable.
* Whether missing values are present.
* Whether duplicate records exist.
* The statistical characteristics of the numerical features.
* The number of observations belonging to each Iris species.

These checks will help identify any data-quality issues that need to be addressed before model development.

In [11]:
# checking the shape of the Dataset

print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 150
Number of columns: 6

In [13]:
# Checking column names

print("Column names:")
for column in df.columns:
    print("--->", column)

Column names:
---> Id
---> SepalLengthCm
---> SepalWidthCm
---> PetalLengthCm
---> PetalWidthCm
---> Species

In [14]:
#checking the data type

print("Data types:")
print(df.dtypes)

Data types:
Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [17]:
# Checking Missing values

print("Missing values:")
df.isnull().sum()

Missing values:

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [20]:
#checking Duplicates

print("Duplicates: ", df.duplicated().sum())

Duplicates:  0

In [22]:
# Checking the number of different species

print("Number of observations per species:")
print(df["Species"].value_counts())

Number of observations per species:
Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [23]:
# Summary Statistics

print("Summary statistics:")
df.describe()

Summary statistics:

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000